definitions:
  handlers.errorRs:
    properties:
      error:
        type: string
    type: object
  handlers.gameStateDto:
    properties:
      board:
        items:
          items:
            type: integer
          type: array
        type: array
      current_player:
        type: integer
      id:
        type: integer
      size:
        type: integer
      type:
        type: string
      winner:
        type: integer
    type: object
  handlers.loginRq:
    properties:
      nickname:
        type: string
      password:
        type: string
    type: object
  handlers.loginRs:
    properties:
      token:
        type: string
    type: object
  handlers.moveGameRq:
    properties:
      col:
        type: integer
      row:
        type: integer
    type: object
  handlers.registerRq:
    properties:
      nickname:
        type: string
      password:
        type: string
    type: object
  handlers.registerRs:
    properties:
      token:
        type: string
    type: object
  handlers.startGameRq:
    properties:
      board_size:
        type: integer
      game_type:
        type: string
    type: object
info:
  contact: {}
  description: API for Gomoku game
  title: Gomoku API
  version: "1.0"
paths:
  /api/v1/games/:
    post:
      consumes:
      - application/json
      description: Starts a new Gomoku game with the given board size and type.
      parameters:
      - description: Game start request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.startGameRq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.gameStateDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorRs'
      security:
      - BearerAuth: []
      summary: Start a new game
      tags:
      - games
  /api/v1/games/{gameId}:
    get:
      consumes:
      - application/json
      description: Returns the current state of the game by its ID.
      parameters:
      - description: Game ID
        in: path
        name: gameId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.gameStateDto'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorRs'
      security:
      - BearerAuth: []
      summary: Get game state
      tags:
      - games
  /api/v1/games/{gameId}/join:
    put:
      consumes:
      - application/json
      description: Join an existing Gomoku game by its ID.
      parameters:
      - description: Game ID
        in: path
        name: gameId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.gameStateDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorRs'
      security:
      - BearerAuth: []
      summary: Join a game
      tags:
      - games
  /api/v1/games/{gameId}/move:
    put:
      consumes:
      - application/json
      description: Make a move in the game by its ID.
      parameters:
      - description: Game ID
        in: path
        name: gameId
        required: true
        type: integer
      - description: Move request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.moveGameRq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.gameStateDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorRs'
      security:
      - BearerAuth: []
      summary: Make a move
      tags:
      - games
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Authenticates player and returns a JWT token
      parameters:
      - description: Login data
        in: body
        name: loginRq
        required: true
        schema:
          $ref: '#/definitions/handlers.loginRq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.loginRs'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorRs'
      summary: Login player
      tags:
      - auth
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: Creates a new player and returns a JWT token
      parameters:
      - description: Registration data
        in: body
        name: registerRq
        required: true
        schema:
          $ref: '#/definitions/handlers.registerRq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.registerRs'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handlers.errorRs'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorRs'
      summary: Register new player
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
